// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyoFOZtX_xZHOFBonuimXk5CVdxoEBpSI',
    appId: '1:517144691046:web:21bc2026474dcba18c48a7',
    messagingSenderId: '517144691046',
    projectId: 'sweetpet-e5c86',
    authDomain: 'sweetpet-e5c86.firebaseapp.com',
    storageBucket: 'sweetpet-e5c86.appspot.com',
    measurementId: 'G-LE2LFP4D46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvLPq1UDq3D7CIpSJaYOPqZON0IyBEzUQ',
    appId: '1:517144691046:android:10c9933a0fdee6948c48a7',
    messagingSenderId: '517144691046',
    projectId: 'sweetpet-e5c86',
    storageBucket: 'sweetpet-e5c86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV8efUBh8k2aPfWdaYmGpWi0VFVABOACQ',
    appId: '1:517144691046:ios:7a2ee6ed4955e4438c48a7',
    messagingSenderId: '517144691046',
    projectId: 'sweetpet-e5c86',
    storageBucket: 'sweetpet-e5c86.appspot.com',
    iosBundleId: 'com.example.sweetpet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV8efUBh8k2aPfWdaYmGpWi0VFVABOACQ',
    appId: '1:517144691046:ios:1df32554f39a6b128c48a7',
    messagingSenderId: '517144691046',
    projectId: 'sweetpet-e5c86',
    storageBucket: 'sweetpet-e5c86.appspot.com',
    iosBundleId: 'com.example.sweetpet.RunnerTests',
  );
}
